# Generated by Django 4.2.26 on 2025-12-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_category_options_remove_session_client_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client'),
        ),
    ]
