# Generated by Django 4.2.26 on 2025-12-21 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='session',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='base.session'),
            preserve_default=False,
        ),
    ]
