from django.urls import path
from . import views

urlpatterns = [
    path('getsessions/', views.SessionsListCreate.as_view(), name="getSessions"),
    path('newsession/', views.SessionsListCreate.as_view(), name="newSession"),
    path('newclient/', views.ClientListCreate.as_view(), name="newClient"),
    path('getclients/', views.ClientListCreate.as_view(), name="getClients"),
    path('getcategories/', views.CategoryListCreate.as_view(), name="getCategories"),
    path('deletecategory/<int:pk>/',
         views.CategoryRUD.as_view(), name="deleteCategory"),
    path('newcategory/', views.CategoryListCreate.as_view(), name="newCategory"),
    path('getsession/<int:pk>/', views.SessionRUD.as_view(),
         name="getSession"),
    path('getmodels/<int:sessionID>/', views.ModelListCreate.as_view(),
         name="getModels"),
    path('updatesession/<int:pk>/', views.SessionRUD.as_view(),
         name="updateSession"),
    path('deletesession/<int:pk>/', views.SessionRUD.as_view(),
         name="deleteSession"),
    path('deleteclient/<int:pk>/', views.ClientRUD.as_view(),
         name="deleteClient"),
    path('getimages/', views.ImageListCreate.as_view(),
         name="getImages"),
    path('newimage/<int:public_id>/', views.ImageListCreate.as_view(),
         name="newImage"),
    path('getgalleries/', views.GalleryListCreate.as_view(),
         name="getGalleries"),
    path('newgallery/<int:public_id>/', views.GalleryListCreate.as_view(),
         name="newGallery"),
]
